# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "gadgetro-id-lemmy-ui"
primary_region = "sin"

[build]
  image = "dessalines/lemmy-ui:0.18.2"

[deploy]
  strategy = "canary"

[env]
  HOSTNAME = "gadgetro.id"
  LEMMY_UI_HTTPS = "false"
  LEMMY_UI_LEMMY_EXTERNAL_HOST = "gadgetro.id:443"
  LEMMY_UI_LEMMY_INTERNAL_HOST = "gadgetro-id-lemmy.flycast:80"

[http_service]
  internal_port = 1234
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 100

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    restart_limit = 0
    method = "GET"
    path = "/login"
    protocol = "http"
