# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "lemdroid-voyager"
primary_region = "sea"

[build]
  image = "ghcr.io/aeharding/voyager:0.27.0"
  
[env]
  CUSTOM_LEMMY_SERVERS = "lemdro.id"

[http_service]
  internal_port = 5314
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
